services:
  App\Symfony\EndPoint\:
    resource: '../../src/Symfony/EndPoint/*'
    tags: ['controller.service_arguments']

  App\Symfony\EndPoint\Restaurant:
    public: true
    bind:
      $client: '@App\Yelp\Client'
