security:
  providers:
    in_memory: { memory: null }
    users:
      entity:
        class: App\Domain\User

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      logout: ~
      provider: 'users'
      guard:
        authenticators:
          - App\Symfony\Security\TokenAuthenticator

  access_control:
    - { path: ^/restaurants, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/history, roles: ROLE_USER }
