version: '3.7'
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=keskonmange
    networks:
     - internal

  nvinx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nvinx.rule=Host(`api.traefik.test`)"
      - "traefik.http.routers.nvinx.entrypoints=web"
    networks:
     - traefik
     - internal

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './:/usr/src/app'
    env_file:
      - .env
    user: 1000:1000
    networks:
     - internal

networks:
  traefik:
    external:
      name: traefik
  internal:
    driver: bridge
