history_list:
  path: /list
  controller: App\Symfony\EndPoint\History::list
  methods: [ GET ]

history_create:
  path: /create
  controller: App\Symfony\EndPoint\History::create
  methods: [ POST ]
