search:
  path: /search
  controller: App\Symfony\EndPoint\Restaurant::search
  methods: [ GET ]

show:
  path: /{id}
  controller: App\Symfony\EndPoint\Restaurant::show
  methods: [ GET ]
  requirements:
    id: \w+
