App\Domain\History:
  type: entity
  repositoryClass: App\Symfony\Repository\HistoryRepository
  table: history
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    restaurantId:
      type: string
      nullable: false

    restaurantName:
      type: string
      nullable: false

    createdAt:
      type: datetime
      nullable: false

  manyToOne:
    user:
      targetEntity: App\Domain\User
      joinColumn:
        name: user_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
