App\Domain\User:
  type: entity
  repositoryClass: App\Symfony\Repository\UserRepository
  table: user
  uniqueConstraints:
    unique_google_id:
      columns: [ google_id ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    googleId:
      type: string
      nullable: false