version: '3.7'
services:
  mysql:
    image: knplabs/keskonmang-api:mysql-${IMAGE_TAG}
    build:
      context: ..
      dockerfile: docker/mysql/Dockerfile
    restart: on-failure
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=keskonmang
    networks:
     - internal

  app:
    image: knplabs/keskonmang-api:app-${IMAGE_TAG}
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    restart: on-failure
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`api.keskonmang.knpnet.net`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=keskonmang"
      - "traefik.docker.network=traefik"
    networks:
     - traefik
     - internal

  php:
    image: knplabs/keskonmang-api:php-${IMAGE_TAG}
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
      target: php
    restart: on-failure
    env_file:
      - ../.env
    user: 1000:1000
    networks:
     - internal

networks:
  traefik:
    external:
      name: traefik
  internal:
    driver: bridge
